dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: dheguTHSuoZ3eIhUd9RWeUQiLMpx8PBYc9XCCF/PK/BlACE11WysKoP0yQWZVX2bWN97h0YWrOBVsxmyyVv2JAUPk0QHPn73GpPEiHDw3TG1HxW1A3+YjAc6+czoH1daneRfQ1P0ucVkmKoYFBdRQj2AqzHQuqUKdvdYtZmGF6THeqkVDlG12O8+N18nIkaRbMt/yj4gU/aUxNcuup3bSHapHtg96JDqmiHYU4VTwzbqQG4iNgT3qYnOA1uMQv8YZDMhW9UHxnkkzT1pRxOj5kaq+HaYAtILCgB5WFdwHQY74mJQZBdyX13/eEGZxLSH+IhRS0KiwPt5j4ELDSfULJjE6VbuzMLMB0PozEBlazkPpvLiOHbD4DBA6anh1bw5N6EiwiQXwr72B1JhVJcfhaJIUObTE0rXQC/q1a9pbj9siIS1nIVlFHtCqS7byviykDYolceCBQTpDe/MW/rw/fXANx/yuoWo/Gkz6SUvb27KvMnqdUL8SmOtbTne51yYszQNRnK7A+YO1hnKkQk/bLTKn1allowsdVuWdtwEJHD6FYeqWteHq18hedXHwcqULDeCpOeZZj9y+gukAwrlBRC2VIQQgL1XByFtH192nl2Ofhv1TsCAKuRxP6Q6uPYylhI05Hgefl0r0ynJrui4Yt1Zl32d9eLh8VhS55ZuBy8=
