---
- name: Configure MongoDB
  hosts: db
  become: true
  vars:
    mongo_bind_ip: "0.0.0.0" # Variables are defined in "vars"
  tasks: # Block of tasks
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2 # path on local file-template
        dest: /etc/mongod.conf # path on remote hosts
        mode: 0644
      notify: restart mongod
  handlers:
    - name: restart mongod
      service: name=mongod state=restarted
